# name: 'String Generator'
# description: 'Generates arbitrary text'
# inputs:
#   string:  # id of input
#     description: 'Any string'
#     required: false
#     default: 'This is the default string'
# outputs:
#   string:
#     description: "The input string"
#     value: ${{ steps.string-gen.outputs.string }}
# runs:
#   using: "composite"
#   steps:
#     - id: string-gen
#       run: echo "string=$(echo Action running: input was ${{inputs.string}})" >> $GITHUB_OUTPUT
#       shell: bash
#     - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
#       shell: bash
#     - run: script.sh
#       shell: bash


name: 'String-gen'
description: 'return string'
inputs:
  string:  # id of input
    description: 'Any string'
    required: false
    default: 'Default string'
outputs:
  string:
    description: "String-generator"
    value: ${{ steps.string-gen.outputs.string }}
runs:
  using: "composite"
  steps:
    - run: echo Hello, the action is running with the following input, ${{ inputs.string }}.
      shell: bash
    - id: string-gen
      run: echo "string=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: run script
      run: script.sh
      shell: bash
